version: '3.8'

services:
  api-server:
    env_file:
      - .env
    build:
      context: .
      args:
        - API_SERVER_PATH=./cmd/api-server/main.go
    volumes:
      - ./:/app                            # Mount the project directory to /app in the container
      - /app/vendor                        # Exclude the vendor folder
    working_dir: /app                      # Set the working directory inside the container
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      

  postgres:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${DB_USER}            # Use the variable from .env
      POSTGRES_PASSWORD: ${DB_PASSWORD}    # Use the variable from .env
      POSTGRES_DB: ${DB_NAME} 
      PGUSER: ${DB_USER}              # Use the variable from .env
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
