// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package restaurants

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Restaurant struct {
	RestaurantID    int32
	VendorID        pgtype.Int4
	Name            string
	Description     pgtype.Text
	CuisineType     pgtype.Text
	Address         string
	Location        interface{}
	Phone           pgtype.Text
	Email           pgtype.Text
	SeatingCapacity pgtype.Int4
	Status          interface{}
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}

type RestaurantAmenity struct {
	AmenityID    int32
	RestaurantID int32
	AmenityName  pgtype.Text
	IsAvailable  pgtype.Bool
}

type RestaurantHour struct {
	HoursID          int32
	RestaurantID     int32
	DayOfWeek        int32
	OpeningTime      pgtype.Time
	ClosingTime      pgtype.Time
	IsClosed         pgtype.Bool
	SpecialHoursNote pgtype.Text
}

type RestaurantImage struct {
	ImageID      int32
	RestaurantID int32
	ImageUrl     string
	ImageType    interface{}
	IsPrimary    pgtype.Bool
	UploadedAt   pgtype.Timestamp
}

type RestaurantReview struct {
	ReviewID     int32
	UserID       int32
	RestaurantID int32
	Rating       pgtype.Int4
	ReviewText   pgtype.Text
	CreatedAt    pgtype.Timestamp
}
