// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package users

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	UserID        int32
	PhoneNumber   pgtype.Text
	Email         pgtype.Text
	FirstName     pgtype.Text
	LastName      pgtype.Text
	PhoneVerified pgtype.Bool
	CreatedAt     pgtype.Timestamp
	LastLogin     pgtype.Timestamp
}

type UserOauthConnection struct {
	ConnectionID   int32
	UserID         int32
	Provider       string
	ProviderUserID string
	AccessToken    pgtype.Text
	RefreshToken   pgtype.Text
	TokenExpiresAt pgtype.Timestamp
	CreatedAt      pgtype.Timestamp
}
