// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package users

import (
	"context"
)

const getUsers = `-- name: GetUsers :exec
SELECT 1
`

func (q *Queries) GetUsers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, getUsers)
	return err
}
