// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	LogID     int32
	UserID    pgtype.Int4
	VendorID  pgtype.Int4
	Action    string
	Details   []byte
	CreatedAt pgtype.Timestamp
}

type Restaurant struct {
	RestaurantID    int32
	VendorID        pgtype.Int4
	Name            string
	Description     pgtype.Text
	CuisineType     pgtype.Text
	Address         string
	Location        interface{}
	Phone           pgtype.Text
	Email           pgtype.Text
	SeatingCapacity pgtype.Int4
	Status          interface{}
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}

type RestaurantAmenity struct {
	AmenityID    int32
	RestaurantID int32
	AmenityName  pgtype.Text
	IsAvailable  pgtype.Bool
}

type RestaurantHour struct {
	HoursID          int32
	RestaurantID     int32
	DayOfWeek        int32
	OpeningTime      pgtype.Time
	ClosingTime      pgtype.Time
	IsClosed         pgtype.Bool
	SpecialHoursNote pgtype.Text
}

type RestaurantImage struct {
	ImageID      int32
	RestaurantID int32
	ImageUrl     string
	ImageType    interface{}
	IsPrimary    pgtype.Bool
	UploadedAt   pgtype.Timestamp
}

type RestaurantReview struct {
	ReviewID     int32
	UserID       int32
	RestaurantID int32
	Rating       pgtype.Int4
	ReviewText   pgtype.Text
	CreatedAt    pgtype.Timestamp
}

type RushMetricsAggregated struct {
	MetricID         int32
	RestaurantID     int32
	TimeBucket       pgtype.Timestamp
	AverageWaitTime  int32
	AverageOccupancy int32
	DataPoints       int32
	VendorUpdates    int32
	UserUpdates      int32
	CreatedAt        pgtype.Timestamp
}

type User struct {
	UserID        int32
	PhoneNumber   pgtype.Text
	Email         pgtype.Text
	FirstName     pgtype.Text
	LastName      pgtype.Text
	PhoneVerified pgtype.Bool
	CreatedAt     pgtype.Timestamp
	LastLogin     pgtype.Timestamp
}

type UserOauthConnection struct {
	ConnectionID   int32
	UserID         int32
	Provider       string
	ProviderUserID string
	AccessToken    pgtype.Text
	RefreshToken   pgtype.Text
	TokenExpiresAt pgtype.Timestamp
	CreatedAt      pgtype.Timestamp
}

type UserPreference struct {
	PreferenceID    int32
	UserID          int32
	PreferenceKey   pgtype.Text
	PreferenceValue pgtype.Text
}

type UserSavedPlace struct {
	SavedID      int32
	UserID       int32
	RestaurantID int32
	CreatedAt    pgtype.Timestamp
}

type Vendor struct {
	VendorID          int32
	PhoneNumber       string
	Email             pgtype.Text
	BusinessName      string
	ContactPersonName pgtype.Text
	PhoneVerified     pgtype.Bool
	TaxID             pgtype.Text
	GstNumber         pgtype.Text
	IsVerified        pgtype.Bool
	VerificationDate  pgtype.Timestamp
	CreatedAt         pgtype.Timestamp
	LastLogin         pgtype.Timestamp
}

type VendorOauthConnection struct {
	ConnectionID   int32
	VendorID       int32
	Provider       string
	ProviderUserID string
	AccessToken    pgtype.Text
	RefreshToken   pgtype.Text
	TokenExpiresAt pgtype.Timestamp
	CreatedAt      pgtype.Timestamp
}
