name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres_db

      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4 

      - name: Debug - Show Go Environment
        run: go env

      - name: Install dependencies
        run: go mod tidy

      - name: Run gofmt check (fail if files need formatting)
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "Go files need formatting. Run 'gofmt -w .' locally and commit changes."
            exit 1
          fi

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2
          echo "Checking if golangci-lint is installed..."
          $(go env GOPATH)/bin/golangci-lint --version

      - name: Debug - List Files
        run: ls -R

      - name: Debug - List Go Files
        run: find . -name "*.go"

      - name: Debug - Show Current Directory
        run: pwd

      - name: Run golangci-lint
        run: $(go env GOPATH)/bin/golangci-lint run --config=.golangci.yml ./cmd/... ./internal/... ./pkg/...

      - name: Run go vet
        run: go vet ./cmd/... ./internal/... ./pkg/... 

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Verify gosec Installation
        run: $(go env GOPATH)/bin/gosec --version

      - name: Run gosec security check
        run: $(go env GOPATH)/bin/gosec ./cmd/... ./internal/... ./pkg/...

      - name: Run tests
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: go test ./cmd/... ./internal/... ./pkg/... -v
