name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres_db

      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4 

      - name: Install dependencies
        run: go mod tidy

      - name: Run gofmt check (fail if files need formatting)
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "Go files need formatting. Run 'gofmt -w .' locally and commit changes."
            exit 1
          fi
 
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --config=.golangci.yml --timeout=5m --path-prefix=rush-free-server

      - name: Run go vet
        run: go vet ./...

      - name: Run go security check
        uses: securego/gosec@v2
        with:
          args: ./...

      - name: Run tests
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: go test ./... -v

