name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres_db

      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: go test ./... -v

      - name: Build Docker Image
        run: docker build -t rush-free-server:staging .

  deploy-to-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'pull_request' && github.event.action == 'opened' || github.event.action == 'synchronize'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4-

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image to Docker Hub
        run: |
          docker tag rush-free-server:staging ${{ secrets.DOCKERHUB_USERNAME }}/rush-free-server:staging
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rush-free-server:staging

      - name: Deploy to Staging 
        uses: kubernetes/deploy-action@v1
        with:
          cluster: ${{ secrets.KUBERNETES_CLUSTER }}
          token: ${{ secrets.KUBERNETES_TOKEN }}
          deployment: rush-free-server-staging
          image: ${{ secrets.DOCKERHUB_USERNAME }}/rush-free-server:staging
